#!/usr/bin/env python
import sys
import subprocess
from PIL import Image
import tempfile

#log = open("/tmp/solidworks-thumbnailer",'a')
#log.write(" ".join(sys.argv) + "\n")
#log.close()

inputname, outputname, size = sys.argv[1:]

f = tempfile.TemporaryFile()

P = subprocess.Popen(['/usr/bin/gsf','cat',inputname,'PreviewPNG'],stdout=f)

out,err = P.communicate()

f.seek(0)

s = int(size)
#print "resizing to %d"%s

im = Image.open(f)
im.thumbnail((s,s), Image.ANTIALIAS)
im.save(outputname, "PNG")
